### ISSUE TITLE
サインイン状態について

### ISSUE THREAD

**Issue by chiro0114** [chiro0114/mavs-task#2]
現状サインインした後にページをリロード・URLを直で叩くとサインイン状態が解除される状態となっていますが、こちらはログイン状態をセッションなどで保存する機能は必須でしょうか？

**Comment by p-t-a-p-1** [comment]
@chiro0114 

> ログイン状態をセッションなどで保存する機能

こちらは対応必須機能ではありません！各々にお任せしております..！
